## data directories
exp_date: '20230814:134500'
prompt: True
cond: True
output_lyrics_dir: './outputs'

enc_tknzr_dir: '/data1/qihao/XAI-Lyricist/bart/bart_tokenizer'
custom_model_dir: '/data1/qihao/XAI-Lyricist/bart/bart_custom_model'
dec_tknzr_dir: 'facebook/bart-base'
model_dir: 'facebook/bart-base'

## Genre Classification Dataset
dataset_dir: './dataset/custom_sample'
binary_data_dir: './binary'  ## dictionaries
word_data_dir: './dataset/custom_sample/binary'
tensorboard: '/data1/qihao/XAI-Lyricist/tensorboards/bart'
checkpoint_dir: '/data1/qihao/XAI-Lyricist/checkpoints/bart'

midi_dir: '/data1/qihao/XAI-Lyricist/MIDI-Lyric'
parse: 'Syllable_Parsing'

pretrain: '/data1/qihao/XAI-Lyricist/checkpoints/bart/BartForConditionalGeneration_20230803:013018_lr5e-05/bestM2LCkpt.pt'

total_epoch: 1000

sentence_maxlen: 1024
hidden_size: 768
# hidden_size: 1024  ## for bart large
drop_prob: 0.2  ## dropout probability for embedding layer
batch_size: 4
d_model: 512
max_len: 1024
ffn_hidden: 2048
n_head: 8
n_layers: 6
warmup: 2500

lambda_rem: 0.0
lambda_word: 1.0

lr: 5.0e-5
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0.001

# early stopping
patience: 5

## loss parameter
lambda_word: 1.0
lambda_syllable: 1.0